server:
  port: 8080

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/finance_db
    url: jdbc:postgresql://host.docker.internal:5432/finance_db
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  secret: secret-key-for-jwt-very-secret-123456
  expiration: 86400000
